#!/usr/bin/env bash
set -euo pipefail

DNS_SERVERS="${DNS_SERVERS:-1.1.1.1 8.8.8.8}"
DRY_RUN="${DRY_RUN:-0}"

log(){ echo "==> $*"; }
die(){ echo "ERROR: $*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Запусти от root"

# WAN = int with default route
WAN_IF="$(ip -4 route show default 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="dev"){print $(i+1); exit}}')"
[[ -n "${WAN_IF}" ]] || die "Не найден default route (WAN)"

# LAN = another int
LAN_IF=""
for i in $(ls /sys/class/net); do
  [[ "$i" == "lo" || "$i" == "$WAN_IF" ]] && continue
  [[ -e "/sys/class/net/$i/device" ]] || continue
  LAN_IF="$i"
  break
done
[[ -n "${LAN_IF}" ]] || die "Не найден LAN интерфейс"

log "WAN интерфейс: $WAN_IF"
log "LAN интерфейс: $LAN_IF"

# WAN CIDR && GW (pin at static interface)
WAN_CIDR="$(ip -4 -o addr show dev "$WAN_IF" | awk '{print $4}' | head -n1)"
WAN_GW="$(ip -4 route show default dev "$WAN_IF" | awk '{print $3; exit}')"
[[ -n "${WAN_CIDR}" ]] || die "На WAN ($WAN_IF) нет IPv4 адреса"
[[ -n "${WAN_GW}" ]]   || die "Не найден шлюз для WAN ($WAN_IF)"

# LAN CIDR: if there is no address, set the default
LAN_CIDR="$(ip -4 -o addr show dev "$LAN_IF" | awk '{print $4}' | head -n1 || true)"
LAN_CIDR="${LAN_CIDR:-192.168.0.1/24}"

cidr2mask() {
  python3 - "$1" <<'PY'
import ipaddress, sys
print(ipaddress.ip_interface(sys.argv[1]).network.netmask)
PY
}

WAN_IP="${WAN_CIDR%/*}"
LAN_IP="${LAN_CIDR%/*}"
WAN_MASK="$(cidr2mask "$WAN_CIDR")"
LAN_MASK="$(cidr2mask "$LAN_CIDR")"

log "WAN будет: $WAN_IP $WAN_MASK gw $WAN_GW"
log "LAN будет: $LAN_IP $LAN_MASK"

interfaces="/etc/network/interfaces"
backup="${interfaces}.bak.$(date +%F_%H%M%S)"

content="$(cat <<EOF
# Generated by ./st (auto static)
source /etc/network/interfaces.d/*

auto lo
iface lo inet loopback

# WAN
auto ${WAN_IF}
iface ${WAN_IF} inet static
    address ${WAN_IP}
    netmask ${WAN_MASK}
    gateway ${WAN_GW}
    dns-nameservers ${DNS_SERVERS}

# LAN
auto ${LAN_IF}
iface ${LAN_IF} inet static
    address ${LAN_IP}
    netmask ${LAN_MASK}
EOF
)"

if [[ "$DRY_RUN" == "1" ]]; then
  log "DRY_RUN=1: ничего не пишу. Было бы записано в $interfaces:"
  echo "-----"
  echo "$content"
  echo "-----"
  exit 0
fi

cp -a "$interfaces" "$backup" 2>/dev/null || true
printf "%s\n" "$content" > "$interfaces"
log "Сохранено. Бэкап: $backup"

# Apply
if systemctl list-unit-files | grep -q '^networking\.service'; then
  systemctl restart networking
else
  service networking restart || true
fi

log "Готово. Проверка:"
ip -br a
ip route show default || true
